title: ShameOnCitizens
description: A collective of individuals urging Citizens Bank to divest from Sunoco Logistics, responsible for the Dakota Access Pipeline and other Pipeline projects.
theme: jekyll-theme-cayman
